<a href="https://colab.research.google.com/github/andresit02/-M-todos-Num-ricos---Tarea-10/blob/main/Tarea_10_Ejercicios_Unidad_04_C_%7C_Descomposici%C3%B3n_LU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### ***Realizado por: Andres P. Fernandez O.***

## CONJUNTO DE EJERCICIOS

1. Realice las siguientes multiplicaciones matriz-matriz:
- a.
\begin{bmatrix}
2 & -3 \\
3 & -1
\end{bmatrix}

\begin{bmatrix}
1 & 5 \\
3 & 0
\end{bmatrix}

- b.
\begin{bmatrix}
2 & -3 \\
3 & -1
\end{bmatrix}

\begin{bmatrix}
1 & 5 & -4 \\
-3 & 2 & 0
\end{bmatrix}

- c.
\begin{bmatrix}
2 & -3 & 1 \\
4 & 3 & 0 \\
5 & 2 & -4
\end{bmatrix}

\begin{bmatrix}
0 & 1 & -2 \\
1 & 0 & -1 \\
2 & 3 & -2
\end{bmatrix}

- d.
\begin{bmatrix}
2 & 1 & 2 \\
-2 & 3 & 0 \\
2 & -1 & 3
\end{bmatrix}

\begin{bmatrix}
1 & -2 \\
-4 & 1 \\
0 & -2
\end{bmatrix}

In [1]:
import numpy as np

# Definir las matrices
A1 = np.array([[2, -3], [3, -1]])
B1 = np.array([[1, 5], [3, 0]])

A2 = np.array([[2, -3], [3, -1]])
B2 = np.array([[1, 5, -4], [-3, 2, 0]])

A3 = np.array([[2, -3, 1], [4, 3, 0], [5, 2, -4]])
B3 = np.array([[0, 1, -2], [1, 0, -1], [2, 3, -2]])

A4 = np.array([[2, 1, 2], [-2, 3, 0], [2, -1, 3]])
B4 = np.array([[1, -2], [-4, 1], [0, -2]])

# Realizar las multiplicaciones
C1 = np.dot(A1, B1)
C2 = np.dot(A2, B2)
C3 = np.dot(A3, B3)
C4 = np.dot(A4, B4)

# Imprimir los resultados
print("Resultado de la multiplicación A1 * B1:")
print(C1)
print("\nResultado de la multiplicación A2 * B2:")
print(C2)
print("\nResultado de la multiplicación A3 * B3:")
print(C3)
print("\nResultado de la multiplicación A4 * B4:")
print(C4)

Resultado de la multiplicación A1 * B1:
[[-7 10]
 [ 0 15]]

Resultado de la multiplicación A2 * B2:
[[ 11   4  -8]
 [  6  13 -12]]

Resultado de la multiplicación A3 * B3:
[[ -1   5  -3]
 [  3   4 -11]
 [ -6  -7  -4]]

Resultado de la multiplicación A4 * B4:
[[ -2  -7]
 [-14   7]
 [  6 -11]]
