<a href="https://colab.research.google.com/github/andresit02/-M-todos-Num-ricos---Tarea-10/blob/main/Tarea_10_Ejercicios_Unidad_04_C_%7C_Descomposici%C3%B3n_LU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### ***Realizado por: Andres P. Fernandez O.***

## CONJUNTO DE EJERCICIOS

1. Realice las siguientes multiplicaciones matriz-matriz:
- a.
\begin{bmatrix}
2 & -3 \\
3 & -1
\end{bmatrix}

\begin{bmatrix}
1 & 5 \\
3 & 0
\end{bmatrix}

- b.
\begin{bmatrix}
2 & -3 \\
3 & -1
\end{bmatrix}

\begin{bmatrix}
1 & 5 & -4 \\
-3 & 2 & 0
\end{bmatrix}

- c.
\begin{bmatrix}
2 & -3 & 1 \\
4 & 3 & 0 \\
5 & 2 & -4
\end{bmatrix}

\begin{bmatrix}
0 & 1 & -2 \\
1 & 0 & -1 \\
2 & 3 & -2
\end{bmatrix}

- d.
\begin{bmatrix}
2 & 1 & 2 \\
-2 & 3 & 0 \\
2 & -1 & 3
\end{bmatrix}

\begin{bmatrix}
1 & -2 \\
-4 & 1 \\
0 & -2
\end{bmatrix}

In [1]:
import numpy as np

# Definir las matrices
A1 = np.array([[2, -3], [3, -1]])
B1 = np.array([[1, 5], [3, 0]])

A2 = np.array([[2, -3], [3, -1]])
B2 = np.array([[1, 5, -4], [-3, 2, 0]])

A3 = np.array([[2, -3, 1], [4, 3, 0], [5, 2, -4]])
B3 = np.array([[0, 1, -2], [1, 0, -1], [2, 3, -2]])

A4 = np.array([[2, 1, 2], [-2, 3, 0], [2, -1, 3]])
B4 = np.array([[1, -2], [-4, 1], [0, -2]])

# Realizar las multiplicaciones
C1 = np.dot(A1, B1)
C2 = np.dot(A2, B2)
C3 = np.dot(A3, B3)
C4 = np.dot(A4, B4)

# Imprimir los resultados
print("Resultado de la multiplicación A1 * B1:")
print(C1)
print("\nResultado de la multiplicación A2 * B2:")
print(C2)
print("\nResultado de la multiplicación A3 * B3:")
print(C3)
print("\nResultado de la multiplicación A4 * B4:")
print(C4)

Resultado de la multiplicación A1 * B1:
[[-7 10]
 [ 0 15]]

Resultado de la multiplicación A2 * B2:
[[ 11   4  -8]
 [  6  13 -12]]

Resultado de la multiplicación A3 * B3:
[[ -1   5  -3]
 [  3   4 -11]
 [ -6  -7  -4]]

Resultado de la multiplicación A4 * B4:
[[ -2  -7]
 [-14   7]
 [  6 -11]]


2. Determine cuáles de las siguientes matrices son no singulares y calcule la inversa de esas matrices:

- a.
\begin{bmatrix}
4 & 2 & 6 \\
3 & 0 & 7 \\
-2 & -1 & -3
\end{bmatrix}

- b.
\begin{bmatrix}
1 & 2 & 0 \\
2 & 1 & -1 \\
3 & 1 & 1
\end{bmatrix}

- c.
\begin{bmatrix}
1 & 1 & -1 & 1 \\
1 & 2 & -4 & -2 \\
2 & 1 & 1 & 5 \\
-1 & 0 & -2 & -4
\end{bmatrix}

- d.
\begin{bmatrix}
4 & 0 & 0 & 0 \\
6 & 7 & 0 & 0 \\
9 & 11 & 1 & 0 \\
5 & 4 & 1 & 1
\end{bmatrix}

In [2]:
def determinant_2x2(matrix):
    """Calcula el determinante de una matriz 2x2."""
    a, b, c, d = matrix[0][0], matrix[0][1], matrix[1][0], matrix[1][1]
    return a * d - b * c

def inverse_2x2(matrix):
    """Calcula la inversa de una matriz 2x2."""
    det = determinant_2x2(matrix)
    if det == 0:
        return None
    a, b, c, d = matrix[0][0], matrix[0][1], matrix[1][0], matrix[1][1]
    return [[d / det, -b / det], [-c / det, a / det]]

def determinant_3x3(matrix):
    """Calcula el determinante de una matriz 3x3."""
    a, b, c = matrix[0]
    d, e, f = matrix[1]
    g, h, i = matrix[2]
    return a * (e * i - f * h) - b * (d * i - f * g) + c * (d * h - e * g)

def cofactor(matrix):
    """Calcula la matriz de cofactores de una matriz 3x3."""
    cofactors = []
    for i in range(3):
        row = []
        for j in range(3):
            minor = [row[:j] + row[j+1:] for row in (matrix[:i] + matrix[i+1:])]
            minor_det = determinant_2x2(minor)
            sign = (-1) ** (i + j)
            row.append(sign * minor_det)
        cofactors.append(row)
    return list(map(list, zip(*cofactors)))  # Transponer la matriz de cofactores

def inverse_3x3(matrix):
    """Calcula la inversa de una matriz 3x3."""
    det = determinant_3x3(matrix)
    if det == 0:
        return None
    cof = cofactor(matrix)
    return [[elem / det for elem in row] for row in cof]

# Ejemplos de matrices
matrix_2x2 = [[4, 2], [3, 0]]
matrix_3x3 = [[1, 2, 0], [2, 1, -1], [3, 1, 1]]

# Calcular inversas
inv_2x2 = inverse_2x2(matrix_2x2)
inv_3x3 = inverse_3x3(matrix_3x3)

print("Inversa de la matriz 2x2:")
print(inv_2x2)

print("\nInversa de la matriz 3x3:")
print(inv_3x3)

Inversa de la matriz 2x2:
[[-0.0, 0.3333333333333333], [0.5, -0.6666666666666666]]

Inversa de la matriz 3x3:
[[-0.25, 0.25, 0.25], [0.625, -0.125, -0.125], [0.125, -0.625, 0.375]]


3. Resuelva los sistemas lineales 4 x 4 que tienen la misma matriz de coeficientes:

X1-X2+2X3 X4 = 6, -
X1 - - X3+ X4 = 4,
2x1+x2+3x3-4x4 = -2,
-X2 X3 X4 =

X1-X2+2X3 X4 = 1,
X1 - X3+ X4 = 1,
2x1+x2+3x3-4x4 = 2,
-X2 X3 X4 = -1. 5;

In [3]:
def gauss_jordan(A, B):
    """ Resuelve el sistema de ecuaciones Ax = B usando el método de Gauss-Jordan. """
    n = len(A)
    M = [row[:] + [b] for row, b in zip(A, B)]  # Augmented matrix

    # Convertir a forma escalonada
    for i in range(n):
        # Buscar el pivote
        max_row = max(range(i, n), key=lambda r: abs(M[r][i]))
        M[i], M[max_row] = M[max_row], M[i]

        # Normalizar la fila del pivote
        pivot = M[i][i]
        if pivot == 0:
            raise ValueError("El sistema es singular")
        M[i] = [x / pivot for x in M[i]]

        # Eliminar las otras filas
        for j in range(n):
            if i != j:
                factor = M[j][i]
                M[j] = [M[j][k] - factor * M[i][k] for k in range(n + 1)]

    # Extraer la solución
    return [row[-1] for row in M]

# Matriz de coeficientes
A = [
    [1, -1, 2, 1],
    [1, 0, -1, 1],
    [2, 1, 3, -4],
    [0, -1, 1, 1]
]

# Vectores de constantes
B1 = [6, 4, -2, 5]
B2 = [1, 1, 2, -1]

# Resolver los sistemas
solution_1 = gauss_jordan(A, B1)
solution_2 = gauss_jordan(A, B2)

print("Solución del Sistema 1:")
print(solution_1)

print("\nSolución del Sistema 2:")
print(solution_2)

Solución del Sistema 1:
[3.5, -9.5, -2.4999999999999996, -1.9999999999999996]

Solución del Sistema 2:
[0.5, 4.5, 1.5, 2.0]


4. Encuentre los valores de A que hacen que la siguiente matriz sea singular

a =
\begin{bmatrix}
1 & -1 & a \\
2 & 2 & 1 \\
0 & a & 3/2
\end{bmatrix}

In [4]:
from sympy import symbols, Matrix, Eq, solve

# Definir el símbolo para 'a'
a = symbols('a')

# Definir la matriz con el parámetro 'a'
matrix = Matrix([
    [1, -1, a],
    [2, 2, 1],
    [0, a, 3/2]
])

# Calcular el determinante de la matriz
determinant = matrix.det()

# Encontrar el valor de 'a' que hace que el determinante sea cero
solutions = solve(Eq(determinant, 0), a)

# Imprimir el resultado
print("Determinante de la matriz en función de 'a':")
print(determinant)
print("\nValores de 'a' que hacen que la matriz sea singular:")
print(solutions)

Determinante de la matriz en función de 'a':
2*a**2 - a + 6.0

Valores de 'a' que hacen que la matriz sea singular:
[0.25 - 1.71391365010026*I, 0.25 + 1.71391365010026*I]


5. Resuelva los siguientes sistemas lineales:

- a.
\begin{bmatrix}
1 & 0 & 0 \\
2 & 1 & 0 \\
-1 & 0 & 1
\end{bmatrix}

\begin{bmatrix}
1 & 0 & 0 \\
2 & 1 & 0 \\
-1 & 0 & 1
\end{bmatrix}

\begin{bmatrix}
x1 \\
x2 \\
x3
\end{bmatrix}

=

\begin{bmatrix}
2 \\
-1 \\
1
\end{bmatrix}

- a.
\begin{bmatrix}
2 & 0 &
0 \\-1 & 1 &
00 \3 & 2 & -1 1
\end{bmatrix}

\begin{bmatrix1 & 1 & 1 0 \0 & 1 & 2 0 \0 & 0 & 1 1
\end{bmatrix}

\begin{bmatrix}
x1 \\
x2 \\
x3
\end{bmatrix}

=

\begin{bmatrix-1
2 \3 -1\0
1
\end{bmatrix}trix}
1 & 0 & 0 \\
2 & 1 & 0 \\
-101
\end{bmatrix}

In [5]:
import numpy as np

# Definir las matrices y vectores
A1 = np.array([
    [1, 0, 0],
    [2, 1, 0],
    [-1, 0, 1]
])

B1 = np.array([2, -1, 1])

A2 = np.array([
    [2, 0, 0],
    [-1, 1, 0],
    [3, 2, -1]
])

B2 = np.array([
    [1, 1, 1],
    [0, 1, 2],
    [0, 0, 1]
])

C2 = np.array([-1, 3, 0])

# Resolver el sistema a
x1 = np.linalg.solve(A1, B1)

# Resolver el sistema b
# Primero, encontrar la inversa de B2
B2_inv = np.linalg.inv(B2)
# Luego, resolver el sistema usando la inversa
x2 = np.linalg.solve(A2 @ B2_inv, C2)

print("Solución del sistema a:")
print(x1)

print("\nSolución del sistema b:")
print(x2)

Solución del sistema a:
[ 2. -5.  3.]

Solución del sistema b:
[5.5 9.5 3.5]
